<template>
  <div class="app-container">
    <el-form :inline="true" size="small" :model="query"><el-form-item label="订单号"><el-input v-model="query.orderNo" clearable @keyup.enter.native="load" /></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="待发货" value="PENDING_SHIPMENT"/><el-option label="待收货" value="SHIPPED"/><el-option label="已完成" value="COMPLETED"/></el-select></el-form-item><el-form-item><el-button type="primary" icon="el-icon-search" size="mini" @click="load">查询</el-button><el-button icon="el-icon-refresh" size="mini" @click="reset">重置</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="list"><el-table-column prop="orderNo" label="订单号" min-width="180"/><el-table-column prop="receiverName" label="收货人" width="100"/><el-table-column prop="status" label="订单状态" width="100"><template slot-scope="s">{{ orderStatus(s.row.status) }}</template></el-table-column><el-table-column prop="companyName" label="物流公司" width="130"/><el-table-column prop="trackingNo" label="运单号" min-width="170"/><el-table-column label="操作" width="260" fixed="right"><template slot-scope="s"><el-button v-if="s.row.status === 'PENDING_SHIPMENT'" type="text" size="mini" icon="el-icon-truck" v-hasPermi="['mall:logistics:ship']" @click="openShip(s.row)">手工发货</el-button><el-button v-if="s.row.shipmentId" type="text" size="mini" icon="el-icon-location" v-hasPermi="['mall:logistics:query']" @click="openDetail(s.row)">查看轨迹</el-button><el-button v-if="s.row.shipmentId" type="text" size="mini" icon="el-icon-plus" v-hasPermi="['mall:logistics:node']" @click="openNode(s.row)">追加节点</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load"/>
    <el-dialog title="手工发货" :visible.sync="shipDialog" width="480px"><el-form :model="shipForm" label-width="90px"><el-form-item label="物流公司"><el-select v-model="shipForm.companyCode" placeholder="请选择物流公司" filterable><el-option v-for="company in logisticsCompanies" :key="company.code" :label="company.name" :value="company.code"/></el-select></el-form-item><el-form-item label="运单号"><el-input v-model="shipForm.trackingNo" maxlength="128" show-word-limit/></el-form-item></el-form><div slot="footer"><el-button @click="shipDialog=false">取消</el-button><el-button type="primary" :disabled="!shipForm.companyCode || !shipForm.trackingNo" @click="ship">确认发货</el-button></div></el-dialog>
    <el-dialog title="物流轨迹" :visible.sync="detailDialog" width="650px"><el-descriptions v-if="shipment" :column="2" border><el-descriptions-item label="物流公司">{{ shipment.companyName }}</el-descriptions-item><el-descriptions-item label="运单号">{{ shipment.trackingNo }}</el-descriptions-item></el-descriptions><el-timeline><el-timeline-item v-for="node in (shipment ? shipment.nodes : [])" :key="node.nodeId" :timestamp="node.eventTime">{{ node.title }}：{{ node.description }}<span v-if="node.location">（{{ node.location }}）</span></el-timeline-item></el-timeline></el-dialog>
    <el-dialog title="追加物流节点" :visible.sync="nodeDialog" width="520px"><el-form :model="nodeForm" label-width="90px"><el-form-item label="节点状态"><el-select v-model="nodeForm.nodeStatus"><el-option v-for="item in nodeStatuses" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item label="标题"><el-input v-model="nodeForm.title"/></el-form-item><el-form-item label="说明"><el-input v-model="nodeForm.description" type="textarea"/></el-form-item><el-form-item label="地点"><el-input v-model="nodeForm.location"/></el-form-item><el-form-item label="发生时间"><el-date-picker v-model="nodeForm.eventTime" type="datetime" value-format="yyyy-MM-ddTHH:mm:ss"/></el-form-item></el-form><div slot="footer"><el-button @click="nodeDialog=false">取消</el-button><el-button type="primary" @click="saveNode">追加节点</el-button></div></el-dialog>
  </div>
</template>
<script>
import { listOrders, getShipment, shipOrder, appendNode } from '@/api/mall/logistics'
export default { name: 'MallLogistics', data () { return { loading: false, list: [], total: 0, query: { pageNum: 1, pageSize: 10, orderNo: undefined, status: undefined }, shipDialog: false, detailDialog: false, nodeDialog: false, shipForm: {}, nodeForm: {}, shipment: null, logisticsCompanies: [{ code: 'SF', name: '顺丰速运' }, { code: 'ZTO', name: '中通快递' }, { code: 'YTO', name: '圆通速递' }, { code: 'STO', name: '申通快递' }, { code: 'YD', name: '韵达速递' }, { code: 'JD', name: '京东物流' }, { code: 'EMS', name: '中国邮政 EMS' }, { code: 'JT', name: '极兔速递' }, { code: 'DEPPON', name: '德邦快递' }], nodeStatuses: [{ value: 'IN_TRANSIT', label: '运输中' }, { value: 'OUT_FOR_DELIVERY', label: '派送中' }, { value: 'DELIVERED', label: '已签收' }, { value: 'EXCEPTION', label: '运输异常' }, { value: 'CORRECTION', label: '更正说明' }] } }, created () { if (this.$route.query.orderNo) this.query.orderNo = this.$route.query.orderNo; this.load() }, methods: { load () { this.loading = true; listOrders(this.query).then(r => { const d = r.data || r; this.list = d.rows || (Array.isArray(d) ? d : []); this.total = d.total || this.list.length }).finally(() => { this.loading = false }) }, reset () { this.query.orderNo = undefined; this.query.status = undefined; this.query.pageNum = 1; this.load() }, orderStatus (s) { return ({ PENDING_SHIPMENT: '待发货', SHIPPED: '待收货', COMPLETED: '已完成' })[s] || s }, openShip (row) { this.shipForm = { orderId: row.orderId, companyCode: '', trackingNo: '' }; this.shipDialog = true }, ship () { shipOrder(this.shipForm.orderId, this.shipForm).then(() => { this.$modal.msgSuccess('发货成功'); this.shipDialog = false; this.load() }) }, openDetail (row) { getShipment(row.shipmentId).then(r => { this.shipment = r.data; this.detailDialog = true }) }, openNode (row) { this.nodeForm = { shipmentId: row.shipmentId, nodeStatus: 'IN_TRANSIT', title: '', description: '', location: '', eventTime: null }; this.nodeDialog = true }, saveNode () { appendNode(this.nodeForm.shipmentId, this.nodeForm).then(() => { this.$modal.msgSuccess('物流节点已追加'); this.nodeDialog = false; this.load() }) } } }
</script>
