import http from './http'
import { getDeviceId } from '../utils/device'

export const sendSmsCode = (phone, challengeTicket = '') => http.post('/mall/member/sms-code', { phone, challengeTicket })
export const createSmsChallenge = phone => http.post('/mall/member/sms-challenge', { phone })
export const verifySmsChallenge = payload => http.post('/mall/member/sms-challenge/verify', payload)
export const loginBySms = payload => http.post('/mall/member/login', { ...payload, deviceId: getDeviceId() })
export const getProfile = () => http.get('/mall/member/profile')
export const getAccountLifecycle = () => http.get('/mall/member/profile/account-lifecycle')
export const startPhoneChange = newPhone => http.post('/mall/member/profile/phone-change', { newPhone })
export const sendPhoneChangeOldCode = requestId => http.post('/mall/member/profile/phone-change/old-code', null, { params: { requestId } })
export const verifyPhoneChangeOld = payload => http.post('/mall/member/profile/phone-change/old-verify', payload)
export const sendPhoneChangeNewCode = payload => http.post('/mall/member/profile/phone-change/new-code', payload)
export const completePhoneChange = payload => http.put('/mall/member/profile/phone-change', payload)
export const sendAccountCancellationCode = () => http.post('/mall/member/profile/account-cancellation/code')
export const cancelMemberAccount = code => http.delete('/mall/member/profile/account', { data: { code } })
export const getAvatarPresets = () => http.get('/mall/member/profile/avatar-presets')
export const updateNickname = nickname => http.put('/mall/member/profile/nickname', { nickname })
export const selectPresetAvatar = presetCode => http.put('/mall/member/profile/avatar/preset', { presetCode })
export const uploadAvatar = file => {
  const body = new FormData()
  body.append('file', file)
  return http.post('/mall/member/profile/avatar/upload', body)
}
export const logoutMember = () => http.post('/mall/member/logout')
export const getMemberSessions = () => http.get('/mall/member/profile/sessions')
export const revokeMemberSession = sessionId => http.delete(`/mall/member/profile/sessions/${sessionId}`)
export const sendPrimaryDeviceCode = () => http.post('/mall/member/profile/sessions/primary-mobile/code')
export const replacePrimaryDevice = code => http.put('/mall/member/profile/sessions/primary-mobile', { code })
export const getAddresses = () => http.get('/mall/member/addresses')
export const addAddress = payload => http.post('/mall/member/addresses', payload)
export const updateAddress = (addressId, payload) => http.put(`/mall/member/addresses/${addressId}`, payload)
export const deleteAddress = addressId => http.delete(`/mall/member/addresses/${addressId}`)
