<template>
  <div class="app-container coupon-admin-page">
    <section class="page-heading"><div><p class="eyebrow">MALL COUPON CENTER · V0.5</p><h1>优惠券运营</h1><p>配置固定金额满减券，结算金额由服务端重新计算；客服售后与财务风控仅可查询。</p></div><el-button v-hasPermi="['mall:coupon:add']" type="primary" icon="el-icon-plus" @click="openCreate">新增优惠券</el-button></section>
    <el-form ref="queryForm" :inline="true" :model="query" size="small" class="query-form">
      <el-form-item label="名称"><el-input v-model="query.keyword" clearable placeholder="优惠券名称" @keyup.enter.native="handleQuery" /></el-form-item>
      <el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部"><el-option label="草稿" value="DRAFT" /><el-option label="已发布" value="PUBLISHED" /><el-option label="已暂停" value="PAUSED" /><el-option label="已结束" value="ENDED" /></el-select></el-form-item>
      <el-form-item><el-button type="primary" icon="el-icon-search" @click="handleQuery">查询</el-button><el-button icon="el-icon-refresh" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-table v-loading="loading" :data="rows" border>
      <el-table-column prop="couponName" label="优惠券" min-width="180" fixed="left" />
      <el-table-column label="规则" min-width="180"><template slot-scope="scope">满 ¥{{ scope.row.thresholdAmount }} 减 ¥{{ scope.row.discountAmount }}</template></el-table-column>
      <el-table-column label="范围" width="110"><template slot-scope="scope">{{ scope.row.scopeType === 'ALL' ? '全场' : scope.row.scopeType === 'CATEGORY' ? '指定分类' : '指定商品' }}</template></el-table-column>
      <el-table-column label="发放" width="130"><template slot-scope="scope">{{ scope.row.claimedQuantity }} / {{ scope.row.totalQuantity }}</template></el-table-column>
      <el-table-column label="有效期" min-width="190"><template slot-scope="scope">{{ scope.row.validFrom }} 至 {{ scope.row.validTo }}</template></el-table-column>
      <el-table-column label="状态" width="100"><template slot-scope="scope"><el-tag size="mini" :type="statusType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column>
      <el-table-column label="操作" width="260" fixed="right"><template slot-scope="scope"><el-button v-hasPermi="['mall:coupon:edit']" type="text" icon="el-icon-edit" :disabled="scope.row.status !== 'DRAFT'" @click="openEdit(scope.row.couponId)">编辑</el-button><el-button v-if="scope.row.status === 'DRAFT' || scope.row.status === 'PAUSED'" v-hasPermi="['mall:coupon:publish']" type="text" icon="el-icon-video-play" @click="changeStatus(scope.row, 'PUBLISHED')">发布</el-button><el-button v-if="scope.row.status === 'PUBLISHED'" v-hasPermi="['mall:coupon:publish']" type="text" icon="el-icon-video-pause" @click="changeStatus(scope.row, 'PAUSED')">暂停</el-button><el-button v-hasPermi="['mall:coupon:issue']" type="text" icon="el-icon-s-promotion" @click="openIssue(scope.row)">手工发放</el-button></template></el-table-column>
    </el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" />

    <el-dialog :title="form.couponId ? '编辑优惠券草稿' : '新增优惠券'" :visible.sync="dialogOpen" width="620px" append-to-body>
      <el-form ref="couponForm" :model="form" :rules="rules" label-width="110px" size="small">
        <el-form-item label="优惠券名称" prop="couponName"><el-input v-model="form.couponName" maxlength="120" /></el-form-item>
        <el-form-item label="适用范围" prop="scopeType"><el-radio-group v-model="form.scopeType"><el-radio-button label="ALL">全场</el-radio-button><el-radio-button label="CATEGORY">指定分类</el-radio-button><el-radio-button label="PRODUCT">指定商品</el-radio-button></el-radio-group></el-form-item>
        <el-row :gutter="12"><el-col :span="12"><el-form-item label="门槛金额" prop="thresholdAmount"><el-input-number v-model="form.thresholdAmount" :min="0" :precision="2" :step="10" /></el-form-item></el-col><el-col :span="12"><el-form-item label="优惠金额" prop="discountAmount"><el-input-number v-model="form.discountAmount" :min="0.01" :precision="2" :step="5" /></el-form-item></el-col></el-row>
        <el-form-item label="发行数量" prop="totalQuantity"><el-input-number v-model="form.totalQuantity" :min="1" :step="10" /></el-form-item>
        <el-form-item label="有效期" prop="validFrom"><el-date-picker v-model="form.validFrom" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" placeholder="开始时间" /></el-form-item><el-form-item label="结束时间" prop="validTo"><el-date-picker v-model="form.validTo" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" placeholder="结束时间" /></el-form-item>
        <el-form-item v-if="form.scopeType !== 'ALL'" label="范围 ID" prop="scopeTargetIds"><el-input v-model="scopeInput" placeholder="分类或 SPU ID，多个用英文逗号分隔" /></el-form-item>
        <el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="500" /></el-form-item>
      </el-form>
      <div slot="footer"><el-button @click="dialogOpen = false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存草稿</el-button></div>
    </el-dialog>
    <el-dialog title="手工发放优惠券" :visible.sync="issueOpen" width="420px" append-to-body><p>将把「{{ issueRow.couponName }}」发放给指定会员，仍受一人限领一次约束。</p><el-input v-model.number="issueMemberId" type="number" placeholder="会员 ID" /><div slot="footer"><el-button @click="issueOpen = false">取消</el-button><el-button type="primary" :loading="issuing" @click="submitIssue">确认发放</el-button></div></el-dialog>
  </div>
</template>

<script>
import { addCoupon, changeCouponStatus, getCoupon, issueCoupon, listCoupon, updateCoupon } from '@/api/mall/coupon'

const emptyForm = () => ({ couponId: undefined, couponName: '', scopeType: 'ALL', thresholdAmount: 100, discountAmount: 10, totalQuantity: 100, validFrom: '', validTo: '', remark: '', scopeTargetIds: [] })
export default { name: 'MallCouponManage', data () { return { loading: false, saving: false, issuing: false, rows: [], total: 0, query: { pageNum: 1, pageSize: 10, keyword: undefined, status: undefined }, form: emptyForm(), scopeInput: '', dialogOpen: false, issueOpen: false, issueRow: {}, issueMemberId: undefined, rules: { couponName: [{ required: true, message: '请输入优惠券名称', trigger: 'blur' }], thresholdAmount: [{ required: true, message: '请输入门槛金额', trigger: 'change' }], discountAmount: [{ required: true, message: '请输入优惠金额', trigger: 'change' }], totalQuantity: [{ required: true, message: '请输入发行数量', trigger: 'change' }], validFrom: [{ required: true, message: '请选择开始时间', trigger: 'change' }], validTo: [{ required: true, message: '请选择结束时间', trigger: 'change' }] } } }, created () { this.load() }, methods: { load () { this.loading = true; listCoupon(this.query).then(response => { this.rows = response.rows || []; this.total = response.total || 0 }).finally(() => { this.loading = false }) }, handleQuery () { this.query.pageNum = 1; this.load() }, resetQuery () { this.query.keyword = undefined; this.query.status = undefined; this.handleQuery() }, openCreate () { this.form = emptyForm(); this.scopeInput = ''; this.dialogOpen = true }, openEdit (id) { getCoupon(id).then(response => { this.form = Object.assign(emptyForm(), response.data); this.scopeInput = (this.form.scopeTargetIds || []).join(','); this.dialogOpen = true }) }, submit () { this.$refs.couponForm.validate(valid => { if (!valid) return; const data = Object.assign({}, this.form, { scopeTargetIds: this.scopeInput.split(',').map(value => Number(value.trim())).filter(value => Number.isInteger(value) && value > 0) }); this.saving = true; const request = data.couponId ? updateCoupon(data) : addCoupon(data); request.then(() => { this.$modal.msgSuccess('草稿已保存'); this.dialogOpen = false; this.load() }).finally(() => { this.saving = false }) }) }, changeStatus (row, status) { this.$modal.confirm(`${status === 'PUBLISHED' ? '发布' : '暂停'}「${row.couponName}」？`).then(() => changeCouponStatus(row.couponId, status)).then(() => { this.$modal.msgSuccess('操作成功'); this.load() }).catch(() => {}) }, openIssue (row) { this.issueRow = row; this.issueMemberId = undefined; this.issueOpen = true }, submitIssue () { if (!this.issueMemberId) return this.$modal.msgError('请输入会员 ID'); this.issuing = true; issueCoupon(this.issueRow.couponId, this.issueMemberId).then(() => { this.$modal.msgSuccess('优惠券已发放'); this.issueOpen = false; this.load() }).finally(() => { this.issuing = false }) }, statusLabel (value) { return ({ DRAFT: '草稿', PUBLISHED: '已发布', PAUSED: '已暂停', ENDED: '已结束' })[value] || value }, statusType (value) { return ({ PUBLISHED: 'success', PAUSED: 'warning', ENDED: 'info' })[value] || '' } } }
</script>

<style scoped>.coupon-admin-page{background:#f5f7fa;min-height:calc(100vh - 84px);color:#303744}.page-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:16px;padding:20px 22px;border:1px solid #e3e8ef;border-left:4px solid #409eff;border-radius:6px;background:#fff}.page-heading h1{margin:4px 0 8px;color:#202b3c;font-size:24px}.page-heading p{margin:0;color:#748094;font-size:13px;line-height:1.6}.eyebrow{color:#2979c7!important;font-size:10px!important;font-weight:700;letter-spacing:.12em}.query-form{padding:16px 16px 4px;border:1px solid #e3e8ef;border-radius:5px;background:#fff}.query-form .el-input{width:210px}.query-form .el-select{width:135px}.el-date-editor{width:100%}</style>
