<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getAdminBrands,getAdminCategories,saveBrand,saveCategory } from '../api/mall'
const tab=ref('分类'), categories=ref([]),brands=ref([]), dialog=ref(false), type=ref('category')
const form=reactive({categoryName:'',brandName:'',sortNo:0,status:'0'})
async function load(){try{categories.value=(await getAdminCategories()).data.data||[];brands.value=(await getAdminBrands()).data.data||[]}catch{categories.value=[{categoryId:1,categoryName:'家居',sortNo:10,status:'0'}];brands.value=[{brandId:1,brandName:'日常精选',sortNo:10,status:'0'}]}}
function open(kind){type.value=kind;Object.assign(form,{categoryName:'',brandName:'',sortNo:0,status:'0'});dialog.value=true}
async function submit(){try{if(type.value==='category')await saveCategory({...form,parentId:0,level:1});else await saveBrand(form);ElMessage.success('保存成功');dialog.value=false;load()}catch{ElMessage.error('保存失败，请确认后台登录和数据库状态')}}
onMounted(load)
</script>
<template><section><div class="page-title"><div><span class="eyebrow">商品基础资料</span><h1>分类与品牌</h1><p>分类组织商品目录，品牌用于筛选和商品归属。</p></div><button class="solid-button" @click="open(tab==='分类'?'category':'brand')">+ 新建{{ tab }}</button></div><div class="panel table-panel"><div class="table-toolbar"><div class="tabs"><button v-for="x in ['分类','品牌']" :key="x" :class="{active:tab===x}" @click="tab=x">{{x}}</button></div></div><table v-if="tab==='分类'"><thead><tr><th>ID</th><th>分类名称</th><th>排序</th><th>状态</th></tr></thead><tbody><tr v-for="x in categories" :key="x.categoryId"><td>{{x.categoryId}}</td><td>{{x.categoryName}}</td><td>{{x.sortNo}}</td><td><span class="status success">{{x.status==='0'?'启用':'停用'}}</span></td></tr></tbody></table><table v-else><thead><tr><th>ID</th><th>品牌名称</th><th>排序</th><th>状态</th></tr></thead><tbody><tr v-for="x in brands" :key="x.brandId"><td>{{x.brandId}}</td><td>{{x.brandName}}</td><td>{{x.sortNo}}</td><td><span class="status success">{{x.status==='0'?'启用':'停用'}}</span></td></tr></tbody></table></div><el-dialog v-model="dialog" :title="`新建${type==='category'?'分类':'品牌'}`" width="420"><el-form label-position="top"><el-form-item :label="type==='category'?'分类名称':'品牌名称'"><el-input v-model="form[type==='category'?'categoryName':'brandName']"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortNo" :min="0"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></template></el-dialog></section></template>
