<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getAdminBrands,getAdminCategories,getAdminProducts,publishProduct,saveProduct } from '../api/mall'
const products=ref([]),categories=ref([]),brands=ref([]),keyword=ref(''),loading=ref(false),dialog=ref(false)
const form=reactive({spuCode:'',productName:'',subtitle:'',categoryId:null,brandId:null,mainImage:'/assets/chair.jpg',publishStatus:'0',sortNo:0,skuList:[],mediaList:[]})
async function load(){loading.value=true;try{products.value=(await getAdminProducts({productName:keyword.value})).data.data||[];categories.value=(await getAdminCategories()).data.data||[];brands.value=(await getAdminBrands()).data.data||[]}catch{products.value=[{spuId:1,spuCode:'SPU-10001',productName:'北欧原木餐椅',categoryName:'家居',brandName:'日常精选',priceMin:399,priceMax:439,publishStatus:'1'}]}finally{loading.value=false}}
function open(){Object.assign(form,{spuId:null,spuCode:`SPU-${Date.now()}`,productName:'',subtitle:'',categoryId:categories.value[0]?.categoryId||null,brandId:brands.value[0]?.brandId||null,mainImage:'/assets/chair.jpg',publishStatus:'0',sortNo:0,skuList:[{skuCode:`SKU-${Date.now()}`,skuName:'默认规格',specJson:'{}',price:0,marketPrice:0,availableStock:0,status:'1'}],mediaList:[]});dialog.value=true}
function addSku(){form.skuList.push({skuCode:`SKU-${Date.now()}-${form.skuList.length+1}`,skuName:'新规格',specJson:'{}',price:0,marketPrice:0,availableStock:0,status:'1'})}
async function submit(){try{await saveProduct(form);ElMessage.success('商品保存成功');dialog.value=false;load()}catch(e){ElMessage.error(e.response?.data?.msg||'保存失败')}}
async function toggle(row){try{await publishProduct(row.spuId,row.publishStatus==='1'?'0':'1');load()}catch{ElMessage.error('状态修改失败')}}
onMounted(load)
</script>
<template><section><div class="page-title"><div><span class="eyebrow">商品中心</span><h1>SPU 与 SKU</h1><p>SPU 是商品主体，SKU 是带具体规格、价格和可售数量的购买单元。</p></div><button class="solid-button" @click="open">+ 新建商品</button></div><div class="panel table-panel"><div class="table-toolbar"><div class="tabs"><button class="active">商品列表</button></div><div class="table-filters"><input v-model="keyword" placeholder="搜索商品名称" @keyup.enter="load"/><button class="outline-button" @click="load">查询</button></div></div><table v-loading="loading"><thead><tr><th>SPU编码</th><th>商品名称</th><th>分类 / 品牌</th><th>价格区间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in products" :key="row.spuId"><td class="order-no">{{row.spuCode}}</td><td class="product-name">{{row.productName}}</td><td class="muted-text">{{row.categoryName}} / {{row.brandName||'-'}}</td><td>¥{{row.priceMin}}<template v-if="row.priceMax!==row.priceMin"> - {{row.priceMax}}</template></td><td><span class="status" :class="row.publishStatus==='1'?'success':'warning'">{{row.publishStatus==='1'?'在售':'下架'}}</span></td><td><button class="link-button" @click="toggle(row)">{{row.publishStatus==='1'?'下架':'上架'}}</button></td></tr></tbody></table></div><el-dialog v-model="dialog" title="新建商品与 SKU" width="760"><el-form label-position="top"><div class="form-grid"><el-form-item label="商品名称"><el-input v-model="form.productName"/></el-form-item><el-form-item label="SPU 编码"><el-input v-model="form.spuCode"/></el-form-item><el-form-item label="分类"><el-select v-model="form.categoryId"><el-option v-for="x in categories" :key="x.categoryId" :label="x.categoryName" :value="x.categoryId"/></el-select></el-form-item><el-form-item label="品牌"><el-select v-model="form.brandId" clearable><el-option v-for="x in brands" :key="x.brandId" :label="x.brandName" :value="x.brandId"/></el-select></el-form-item></div><el-form-item label="副标题"><el-input v-model="form.subtitle"/></el-form-item><div class="sku-heading"><strong>SKU 规格</strong><el-button size="small" @click="addSku">新增 SKU</el-button></div><div v-for="(sku,i) in form.skuList" :key="i" class="sku-row"><el-input v-model="sku.skuCode" placeholder="SKU编码"/><el-input v-model="sku.skuName" placeholder="规格名称"/><el-input-number v-model="sku.price" :min="0" :precision="2"/><el-input-number v-model="sku.availableStock" :min="0"/></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">保存商品</el-button></template></el-dialog></section></template>
